[package]
name = "chimp_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["code", "cli"]

[dependencies]

[build-dependencies]
rustc_version = "0.4.0"
